# Generated by Django 3.2 on 2022-03-27 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('worker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_desc', models.CharField(blank=True, max_length=300)),
                ('skill_set', models.CharField(blank=True, max_length=200)),
                ('apartment_num', models.IntegerField()),
                ('building_num', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=200)),
                ('assign_to', models.CharField(max_length=200)),
                ('renter_name', models.CharField(max_length=200)),
                ('manager_name', models.CharField(max_length=200)),
                ('promised_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_cost', models.FloatField()),
                ('estimated_cost', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
