# Generated by Django 4.0.3 on 2022-03-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('Local_Building_Manager', 'Local_Building_Manager'), ('Property_Manager', 'Property_Manager'), ('Repair_Crew', 'Repair_Crew')], max_length=100, null=True),
        ),
    ]
