# Generated by Django 3.2 on 2022-03-16 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('apartment_name', models.CharField(blank=True, max_length=200)),
                ('apartment_contact_num', models.IntegerField()),
                ('apartment_comments', models.CharField(blank=True, max_length=200)),
                ('apartment_num', models.IntegerField()),
                ('apartment_building_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(blank=True, max_length=200)),
                ('property_contact_num', models.IntegerField()),
                ('property_apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_apartment_id', to='property.apartment')),
            ],
        ),
    ]
